# Generated by Django 3.2.5 on 2021-12-12 10:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_story', '0002_alter_shortstory_writer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created', '-update']},
        ),
        migrations.AlterField(
            model_name='shortstory',
            name='context',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
