# Generated by Django 3.2.5 on 2021-12-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211210_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='userImage.png', null=True, upload_to=''),
        ),
    ]
